### ISSUE TITLE
Getting an error: "name" [1]: -- missing --  , when starting the server in hapi v17.4.0

### ISSUE THREAD

**Issue by utkj97** [paullang/hapi-mail#8]
Code:
```
const options = { 
    template: {
        engine: 'handlebars',
        path: './templates/' 
    },
    email: {
        engine: 'ses',
        options: { accessKeyId: access_key, secretAccessKey: secret_key, region: 'eu-west-1' },
        defaultFrom: 'abc@gmail.com'
    }
  };

await server.register([{
plugin: require('hapi-mail'),
options: options
}]);

```
I am getting this error when I am trying to run the server: 

```
"name" [1]: -- missing --
  },
  "options": {
    "template": {
      "engine": "handlebars",
      "path": "./templates/"
    },
    "email": {
      "engine": "ses",
      "options": {
        "region": "eu-west-1"
      },
      "defaultFrom": "abc@gmail.com"
    }
  }
}

[1] "name" is required
    at new AssertionError (internal/errors.js:469:11)
    at Object.exports.assert (/home/Utkarsh_Jaiswal/Documents/node-hapi-app/node-hapi-app/node_modules/hoek/lib/index.js:736:11)
    at Object.exports.apply (/home/Utkarsh_Jaiswal/Documents/node-hapi-app/node-hapi-app/node_modules/hapi/lib/config.js:22:10)
    at internals.Server.register (/home/Utkarsh_Jaiswal/Documents/node-hapi-app/node-hapi-app/node_modules/hapi/lib/server.js:392:31)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
(node:8069) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8069) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that arenot handled will terminate the Node.js process with a non-zero exit code.

```
How to resolve this error?

**Comment by createthis** [comment]
@paullang any plans to update this to Hapi v17?

**Comment by createthis** [comment]
PR for this issue (untested yet) https://github.com/paullang/hapi-mail/pull/9
